package com.mgudux.mail2ticket.domain.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Email;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "emails")
public class EmlFile {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, unique = true)
    private UUID id;

    // Every .EML contains a unique ID generated by the email server.
    // We can use this to prevent that the same email is analyzed twice
    @Column(name = "message_id", unique = true)
    private String messageId;

    @NotBlank
    @Email
    @Column(name = "sender_email", nullable = false)
    private String senderEmail;

    @NotBlank
    @Column(name = "sender_name", nullable = false)
    private String senderName;

    @ElementCollection
    @CollectionTable(name = "email_receivers", joinColumns = @JoinColumn(name = "eml_file_id"))
    @Column(name = "address", nullable = false)
    private List<String> receiverEmail;

    @ElementCollection
    @CollectionTable(name = "email_cc", joinColumns = @JoinColumn(name = "eml_file_id"))
    @Column(name = "address")
    private List<String> carbonCopy;

    @Column(name = "subject")
    private String subject;

    @Column(name = "body", columnDefinition = "TEXT")
    private String body;

    @ElementCollection
    @CollectionTable(name = "email_attachments", joinColumns = @JoinColumn(name = "eml_file_id"))
    @Column(name = "name")
    private List<String> attachmentNames;

    // AWS s3 predesigned URL to find the uploaded raw .EML
    @Column(name = "raw_email_key")
    private String rawEmailKey;

    // Was this email successfully extracted into a Ticket?
    @Enumerated(EnumType.STRING)
    @Column(name = "processing_status", nullable = false)
    private ProcessingStatus processingStatus = ProcessingStatus.MANUAL_CHECK_REQUIRED;

    @Column(name = "error_message")
    private String errorMessage;

    @Column(name = "sent", nullable = false, updatable = false)
    private LocalDateTime sent;

    @CreationTimestamp
    @Column(name = "created", nullable = false, updatable = false)
    private LocalDateTime created;

    @UpdateTimestamp
    @Column(name = "updated", nullable = false)
    private LocalDateTime updated;

    @OneToOne(mappedBy = "email", cascade = CascadeType.DETACH)
    private Ticket ticket;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private Customer customer;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmlFile)) return false;
        EmlFile other = (EmlFile) o;
        return id != null && id.equals(other.getId());
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return "EmlFile{" +
                "id=" + id +
                ", messageId='" + messageId + '\'' +
                ", senderEmail='" + senderEmail + '\'' +
                ", senderName='" + senderName + '\'' +
                ", receiverEmail=" + receiverEmail +
                ", carbonCopy=" + carbonCopy +
                ", subject='" + subject + '\'' +
                ", body='" + body + '\'' +
                ", attachmentNames=" + attachmentNames +
                ", rawEmailKey='" + rawEmailKey + '\'' +
                ", processingStatus=" + processingStatus +
                ", errorMessage='" + errorMessage + '\'' +
                ", sent=" + sent +
                ", created=" + created +
                ", updated=" + updated +
                '}';
    }
}